name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: online-sales-cluster

jobs:
  build:
    name: Build y Push imágenes
    runs-on: ubuntu-latest

    outputs:
      backend-image: ${{ steps.build-backend.outputs.image }}
      payment-image: ${{ steps.build-payment.outputs.image }}
      frontend-image: ${{ steps.build-frontend.outputs.image }}

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # BACKEND
      - name: Build y push Backend
        id: build-backend
        run: |
          IMAGE=${{ steps.login-ecr.outputs.registry }}/backend-fastapi:latest

          docker build -t $IMAGE ./backend-fastapi
          docker push $IMAGE

          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      # PAYMENT
      - name: Build y push Payment
        id: build-payment
        run: |
          IMAGE=${{ steps.login-ecr.outputs.registry }}/payment-service:latest

          docker build -t $IMAGE ./payment-service
          docker push $IMAGE

          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      # FRONTEND
      - name: Build y push Frontend
        id: build-frontend
        run: |
          IMAGE=${{ steps.login-ecr.outputs.registry }}/frontend-angular:latest

          docker build --no-cache -t $IMAGE ./frontend-angular
          docker push $IMAGE

          echo "image=$IMAGE" >> $GITHUB_OUTPUT

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Render task definition backend
        id: render-backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-def-backend.json
          container-name: backend
          image: ${{ needs.build.outputs.backend-image }}

      - name: Deploy ECS Backend
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-backend.outputs.task-definition }}
          service: backend-service
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

  deploy-payment:
    name: Deploy Payment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Inyectar variables
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          sed -i "s/ACCOUNT_ID/$ACCOUNT_ID/g" .aws/task-def-payment.json
          sed -i "s|MP_TOKEN_PLACEHOLDER|${{ secrets.MERCADOPAGO_ACCESS_TOKEN }}|g" .aws/task-def-payment.json
          sed -i "s|MP_PUBLIC_KEY_PLACEHOLDER|${{ secrets.MERCADOPAGO_PUBLIC_KEY }}|g" .aws/task-def-payment.json

      - name: Render task definition payment
        id: render-payment
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-def-payment.json
          container-name: payment
          image: ${{ needs.build.outputs.payment-image }}

      - name: Deploy ECS Payment
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-payment.outputs.task-definition }}
          service: payment-service
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Render task definition frontend
        id: render-frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-def-frontend.json
          container-name: frontend
          image: ${{ needs.build.outputs.frontend-image }}

      - name: Deploy ECS Frontend
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-frontend.outputs.task-definition }}
          service: frontend-service
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true